### PR TITLE
Use unicode full-block character instead of square.

### PR DESCRIPTION
**Pull request by maffoo**
This removes some of the whitespace in patterns, which IMO makes it
more clear what is going on.

### CODE REVIEW

**Comment by DanielSank** [comment]
I agree with this, as the square character fooled me into thinking some rules generated various horizontal lines that were really just the result of the character being "short".

**Comment by lovesegfault** [comment]
Our terminal library, [rusttty](https://github.com/cpjreynolds/rustty) does not support full-width characters yet. I have opened [an issue](https://github.com/cpjreynolds/rustty/issues/57) showing the problem with that particular unicode character, but the maintainer hasn't responded yet. If we want this to be a thing we may have to move to raw [termion](https://docs.rs/termion/1.5.1/termion/), which I was trying to avoid doing because it's kind of a pain to use.

As I see it this isn't as big of an issue as soon as we have a proper GUI.

**Comment by maffoo** [comment]
Using the full block character from this PR works for me. Do you see problems on some other terminal?

**Comment by maffoo** [comment]
(Note that "full block" is different from "large black square" in the linked issue. It just fills in the space allotted to a character, so the aspect ratio is off, but at least there are no gaps between cells.)

**Comment by lovesegfault** [comment]
Ah, my bad, I had mistaken the unicode then. Originally that's the character I had used, but then I changed to the square because the aspect ratio was bothering me. If both y'all think that the aspect ratio issue is outweighed by the "lines", then I have no problem with going back to the full block, specially since the GUI is on the works.

**Review by lovesegfault — APPROVED** [review]

**Pull request merged**
